### ISSUE TITLE
Crashes Unity for me

### ISSUE THREAD

**Issue by andybak** [omid3098/OpenFlowMap#4]
If you'll excuse my impertinance - I'd like to strongly recommend always publishing the *entire* Unity project. In my experience (and I download a very large number of repos) - it hugely increases the likelihood of things just working and makes it quicker and simpler to try out people's work.

Using this template: https://github.com/adrenak/upm-template you get the best of both worlds as a UPM branch is automatically updated for every commit.

**Comment by omid3098** [comment]
Thank you very much Andy, I agree with you.
Maintaining 2 branches simultaneously slows me down and I was not aware of the pipeline you mentioned.
I will check it out and try to clean things up.

**Comment by omid3098** [comment]
@andybak also if you are good with these kinds of things, I would appreciate PRs!
